server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/crud
    username: postgres
    password: postgres
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.yml
  jackson:
    default-property-inclusion: NON_NULL